services:
  - type: web
    name: gradeflow
    runtime: docker
    plan: free
    healthCheckPath: /up

    envVars:
      - key: APP_NAME
        value: GradeFlow

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: pgsql

      - key: DATABASE_URL
        fromDatabase:
          name: gradeflow-db
          property: connectionString

      - key: ADMIN_EMAIL
        sync: false

      - key: ADMIN_PASSWORD
        sync: false

      - key: SESSION_DRIVER
        value: database

      - key: CACHE_STORE
        value: database

      - key: QUEUE_CONNECTION
        value: sync

      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: gradeflow-db
    plan: free