<?php
use App\Http\Controllers\{AuditLogController,AuthController,ClassAssignmentController,ClassGradebookController,DashboardController,ExportController,GradeRecordController,InstructorController,ProfileController,ReportController,SchoolYearController,SectionController,StudentController,SubjectController,UserAccountController};
use Illuminate\Support\Facades\Route;
Route::redirect('/', '/admin/login');
Route::middleware('guest')->group(function(){
 Route::get('/admin/login',fn()=>app(AuthController::class)->showLogin('admin'))->name('login');Route::post('/admin/login',fn(\Illuminate\Http\Request $request)=>app(AuthController::class)->login($request,'admin'))->name('admin.login.store');
 Route::get('/faculty/login',fn()=>app(AuthController::class)->showLogin('faculty'))->name('faculty.login');Route::post('/faculty/login',fn(\Illuminate\Http\Request $request)=>app(AuthController::class)->login($request,'faculty'))->name('faculty.login.store');
 Route::get('/student/login',fn()=>app(AuthController::class)->showLogin('student'))->name('student.login');Route::post('/student/login',fn(\Illuminate\Http\Request $request)=>app(AuthController::class)->login($request,'student'))->name('student.login.store');
});
Route::middleware(['auth', 'active.account'])->group(function(){
 Route::post('/notifications/seen',function(\Illuminate\Http\Request $request){$request->user()->forceFill(['notifications_seen_at'=>now()])->save();return response()->noContent();})->name('notifications.seen');
 Route::post('/logout',[AuthController::class,'logout'])->name('logout');Route::get('/dashboard',DashboardController::class)->name('dashboard');Route::get('/profile',ProfileController::class)->name('profile.show');Route::put('/profile/password',[ProfileController::class,'updatePassword'])->middleware('role:instructor,student')->name('profile.password.update');
 Route::get('/subjects',[SubjectController::class,'index'])->name('subjects.index');Route::get('/subjects/{subject}',[SubjectController::class,'show'])->whereNumber('subject')->name('subjects.show');
 Route::get('/grades',[GradeRecordController::class,'index'])->name('grades.index');Route::get('/grades/{grade}',[GradeRecordController::class,'show'])->whereNumber('grade')->name('grades.show');
 Route::middleware('role:administrator,registrar,instructor')->group(function(){Route::get('/students',[StudentController::class,'index'])->name('students.index');Route::get('/students/{student}',[StudentController::class,'show'])->whereNumber('student')->name('students.show');Route::get('/classes',[ClassAssignmentController::class,'index'])->name('classes.index');Route::get('/classes/{class}',[ClassAssignmentController::class,'show'])->whereNumber('class')->name('classes.show');Route::get('/grade-entry',[GradeRecordController::class,'create'])->name('grades.create');Route::post('/grades',[GradeRecordController::class,'store'])->name('grades.store');Route::get('/grades/{grade}/edit',[GradeRecordController::class,'edit'])->name('grades.edit');Route::put('/grades/{grade}',[GradeRecordController::class,'update'])->name('grades.update');Route::patch('/grades/{grade}/submit',[GradeRecordController::class,'submit'])->name('grades.submit');});
 Route::middleware('role:instructor')->group(function(){
  Route::get('/faculty/grade-entry',[ClassGradebookController::class,'index'])->name('faculty.grade-entry');
  Route::put('/classes/{class}/gradebook',[ClassGradebookController::class,'save'])->whereNumber('class')->name('classes.gradebook.save');
  Route::post('/classes/{class}/gradebook/submit',[ClassGradebookController::class,'submit'])->whereNumber('class')->name('classes.gradebook.submit');
 });
 Route::middleware('role:administrator,registrar')->group(function(){
  Route::get('/students/create',[StudentController::class,'create'])->name('students.create');Route::post('/students',[StudentController::class,'store'])->name('students.store');Route::get('/students/{student}/edit',[StudentController::class,'edit'])->name('students.edit');Route::put('/students/{student}',[StudentController::class,'update'])->name('students.update');Route::patch('/students/{student}/archive',[StudentController::class,'archive'])->name('students.archive');Route::patch('/students/{student}/restore',[StudentController::class,'restore'])->name('students.restore');
  Route::get('/instructors',[InstructorController::class,'index'])->name('instructors.index');Route::get('/instructors/create',[InstructorController::class,'create'])->name('instructors.create');Route::post('/instructors',[InstructorController::class,'store'])->name('instructors.store');Route::get('/instructors/{instructor}/edit',[InstructorController::class,'edit'])->name('instructors.edit');Route::put('/instructors/{instructor}',[InstructorController::class,'update'])->name('instructors.update');Route::patch('/instructors/{instructor}/archive',[InstructorController::class,'archive'])->name('instructors.archive');Route::patch('/instructors/{instructor}/restore',[InstructorController::class,'restore'])->name('instructors.restore');
  Route::get('/sections',[SectionController::class,'index'])->name('sections.index');Route::get('/sections/create',[SectionController::class,'create'])->name('sections.create');Route::post('/sections',[SectionController::class,'store'])->name('sections.store');Route::get('/sections/{section}/edit',[SectionController::class,'edit'])->name('sections.edit');Route::put('/sections/{section}',[SectionController::class,'update'])->name('sections.update');Route::patch('/sections/{section}/archive',[SectionController::class,'archive'])->name('sections.archive');
  Route::get('/subjects/create',[SubjectController::class,'create'])->name('subjects.create');Route::post('/subjects',[SubjectController::class,'store'])->name('subjects.store');Route::get('/subjects/{subject}/edit',[SubjectController::class,'edit'])->name('subjects.edit');Route::put('/subjects/{subject}',[SubjectController::class,'update'])->name('subjects.update');Route::patch('/subjects/{subject}/archive',[SubjectController::class,'archive'])->name('subjects.archive');
  Route::get('/classes/create',[ClassAssignmentController::class,'create'])->name('classes.create');Route::post('/classes',[ClassAssignmentController::class,'store'])->name('classes.store');Route::patch('/grades/{grade}/release',[GradeRecordController::class,'release'])->name('grades.release');Route::patch('/grades/{grade}/reopen',[GradeRecordController::class,'reopen'])->name('grades.reopen');
  Route::get('/reports',[ReportController::class,'index'])->name('reports.index');Route::get('/reports/pdf',[ReportController::class,'pdf'])->name('reports.pdf');Route::get('/activity-logs',AuditLogController::class)->name('audit.index');Route::get('/user-accounts',[UserAccountController::class,'index'])->name('users.index');Route::put('/user-accounts/{user}',[UserAccountController::class,'update'])->name('users.update');Route::patch('/user-accounts/{user}/reset-student-password',[UserAccountController::class,'resetStudentPassword'])->name('users.reset-student-password');
  Route::get('/exports/students',[ExportController::class,'students'])->name('exports.students');
  Route::get('/school-years',[SchoolYearController::class,'index'])->name('school-years.index');Route::post('/school-years',[SchoolYearController::class,'store'])->name('school-years.store');Route::patch('/school-years/{schoolYear}/activate',[SchoolYearController::class,'activate'])->name('school-years.activate');
 });
 Route::get('/exports/grades',[ExportController::class,'grades'])->name('exports.grades');
});
