<?php
namespace App\Http\Controllers;
use App\Models\{ActivityLog,Instructor,User};use Illuminate\Http\{Request,RedirectResponse};use Illuminate\Support\Facades\{DB,Hash};use Illuminate\Validation\Rule;use Illuminate\View\View;
class InstructorController extends Controller {
 public function index(Request $r):View{$status=$r->input('status','active');$instructors=Instructor::when($status!=='all',fn($q)=>$q->where('status',$status))->paginate(12)->withQueryString();return view('instructors.index',compact('instructors','status'));}
 public function create():View{return view('instructors.form',['instructor'=>new Instructor]);}
 public function store(Request $r):RedirectResponse{$d=$this->validated($r);DB::transaction(function()use($d,$r){$u=User::create(['name'=>$d['first_name'].' '.$d['last_name'],'email'=>$d['email'],'role'=>'instructor','status'=>'active','password'=>Hash::make($d['password'])]);$i=Instructor::create($d+['user_id'=>$u->id,'status'=>'active']);ActivityLog::record('instructor.created',"{$r->user()->name} created instructor {$i->employee_number}.");});return redirect()->route('instructors.index')->with('status','Instructor and account created.');}
 public function edit(Instructor $instructor):View{return view('instructors.form',compact('instructor'));}
 public function update(Request $r,Instructor $instructor):RedirectResponse{$d=$this->validated($r,$instructor);DB::transaction(function()use($d,$instructor,$r){$instructor->update($d);$account=['name'=>$d['first_name'].' '.$d['last_name'],'email'=>$d['email']];if(!empty($d['password']))$account['password']=Hash::make($d['password']);$instructor->user?->update($account);ActivityLog::record('instructor.updated',"{$r->user()->name} updated instructor {$instructor->employee_number}.");});return redirect()->route('instructors.index')->with('status','Instructor and account updated.');}
 public function archive(Request $r,Instructor $instructor):RedirectResponse{$instructor->update(['status'=>'archived']);$instructor->user?->update(['status'=>'inactive']);ActivityLog::record('instructor.archived',"{$r->user()->name} deactivated instructor {$instructor->employee_number}.");return back()->with('status','Instructor deactivated.');}
 public function restore(Request $r,Instructor $instructor):RedirectResponse{$instructor->update(['status'=>'active']);$instructor->user?->update(['status'=>'active']);ActivityLog::record('instructor.restored',"{$r->user()->name} restored instructor {$instructor->employee_number}.");return back()->with('status','Instructor restored.');}
 private function validated(Request $r,?Instructor $i=null):array{return $r->validate(['employee_number'=>['required',Rule::unique('instructors')->ignore($i)],'first_name'=>'required|max:100','middle_name'=>'nullable|max:100','last_name'=>'required|max:100','email'=>['required','email',Rule::unique('instructors')->ignore($i),Rule::unique('users')->ignore($i?->user_id)],'password'=>[$i?'nullable':'required','nullable','min:8']]);}
}
